source/app_data/urls.py
# (c) cavaliba.com - data - urls.py

from django.urls import path

from app_data import views
from app_data import ajax 
from app_data import api

# url namespace
app_name="app_data"

urlpatterns = [

    path('',  views.private, name='private'),

    # api ; in descending order
    path('api/', api.index, name='api_index'),
    path('api/classes/', api.classes, name='api_classes'),
    path('api/c/<slug:classname>/', api.classname, name='api_classname'),
    path('api/c/<slug:classname>/i/<slug:keyname>/', api.instance, name='api_instance'),
    path('api/import/', api.api_import, name='api_import'),
    path('api/csv/<slug:classname>/', api.api_csv, name='api_csv'),

    # anon
    #path('anon',  views.anonymous, name='anonymous'),

    # PRIVATE
    path('private/', views.private, name='private'),
    path('private/', views.private, name='class_list'),
    path('private/c/<slug:classname>/list/', views.instance_list, name='instance_list'),
    path('private/c/<slug:classname>/new/', views.instance_new, name='instance_new'),
    path('private/c/<slug:classname>/i/<str:handle>/detail/', views.instance_detail, name='instance_detail'),
    path('private/c/<slug:classname>/i/<str:handle>/edit/', views.instance_edit, name='instance_edit'),
    path('private/c/<slug:classname>/i/<str:handle>/delete/', views.instance_delete, name='instance_delete'),

    #path('private/import/', views.data_import, name='data_import'),
    path('private/import/', views.data_import, name='data_import'),
    path('private/export/', views.data_export, name='data_export'),

    # ajax 
    path('private/ajax/', ajax.ajax_instance, name='ajax_instance'),

    #path('private/list/', views.list, name='list'),
    #path('private/detail/<int:pageid>/', views.detail, name='detail'),


]

source/app_user/urls.py
# (c) cavaliba.com - IAM - urls.py


from django.urls import path

from app_user import user_views
from app_user import group_views
from app_user import role_views
from app_user import ajax 


# url namespace
app_name="app_user"

urlpatterns = [

 
    # PRIVATE
    path('private/', user_views.private, name='private'),
    #path('private/list/', views.list, name='list'),
    #path('private/detail/<int:pageid>/', views.detail, name='detail'),
    path('private/debug/',  user_views.debug_env  , name='debug'),
    path('private/logout/', user_views.logout , name='logout'),

    # USER
    path('private/users/', user_views.list, name='user_list'),
    #path('private/users/import/', user_views.user_import, name='user_import'),
    path('private/user/detail/<int:userid>/', user_views.detail, name='user_detail'),
    path('private/user/detail/<str:login>/', user_views.detail, name='user_detail'),
    path('private/user/edit/', user_views.edit, name='user_edit'),
    path('private/user/edit/<int:userid>/', user_views.edit, name='user_edit'),
    path('private/user/edit/<str:login>/', user_views.edit, name='user_edit'),
    path('private/user/delete/<int:userid>/', user_views.delete, name='user_delete'),
    path('private/user/pref/', user_views.preferences, name='user_pref'),
    path('private/user/pref/<int:userid>/', user_views.preferences, name='user_pref'),
    path('private/user/email/test/<int:userid>/', user_views.email_test, name='email_test'),
    path('private/user/sms/test/<int:userid>/', user_views.sms_test, name='sms_test'),

    # groups
    path('private/groups/', group_views.list, name='group_list'),
    #path('private/groups/import/', group_views.group_import, name='group_import'),
    path('private/groups/edit/', group_views.edit, name='group_edit'),
    path('private/groups/edit/<int:gid>/', group_views.edit, name='group_edit'),
    path('private/groups/edit/<slug:keyname>/', group_views.edit, name='group_edit'),
    path('private/groups/detail/<int:gid>/', group_views.detail, name='group_detail'),
    path('private/groups/detail/<slug:gname>/', group_views.detail, name='group_detail'),
    path('private/groups/delete/<int:gid>/', group_views.delete, name='group_delete'),


    # roles
    path('private/roles/', role_views.list, name='role_list'),
    #path('private/roles/import/', role_views.role_import, name='role_import'),
    path('private/roles/edit/', role_views.edit, name='role_edit'),
    path('private/roles/edit/<int:gid>/', role_views.edit, name='role_edit'),
    path('private/roles/edit/<slug:keyname>/', role_views.edit, name='role_edit'),    
    path('private/roles/detail/<int:rid>/', role_views.detail, name='role_detail'),
    path('private/roles/detail/<slug:rname>/', role_views.detail, name='role_detail'),
    path('private/roles/delete/<int:gid>/', role_views.delete, name='role_delete'),

    # ajax 
    path('private/ajax/', ajax.ajax_user, name='ajax_user'),

    # api

]

source/core/urls.py
# (c) cavaliba.com - core urls.py

from django.urls import include, path
from django.shortcuts import render, redirect

import debug_toolbar

import app_sirene.public_views
import app_home.views

from django.contrib import admin

admin.site.site_header = 'CAVALIBA DB ADMIN'
admin.site.site_title = 'Cavaliba'
admin.site.site_name = "Cavaliba Admin Tools"


urlpatterns = [

    # /status/   => app_home status
    path('status/', app_home.views.status, name='status'),

    # /  >> /sirene/
    path('', app_sirene.public_views.index),

    # home/  >> app_home
    path('home/', include('app_home.urls')),

    # sirene/
    path('sirene/', include('app_sirene.urls')),
#    path('', include('app_sirene.urls')),

    # user/
    path('user/', include('app_user.urls')),

    # data
    path('data/', include('app_data.urls')),

    # local django auth 
    path("accounts/", include("django.contrib.auth.urls")),

    # django admin
    path('private/admin/', admin.site.urls),
    path('private/tinymce/', include('tinymce.urls')),
    

    path("private/__debug__/", include("debug_toolbar.urls")),

    # Deprecated:  OKTA login Init URI
    #path('private/', lambda request: redirect('app_sirene:private', permanent=False)),


]

source/app_data/models.py
# (c) cavaliba.com - data - models.py

from django.db import models
from django.utils.translation import gettext_lazy as _

# ----------------------------------------------------------------------------------
# DataClass
# ----------------------------------------------------------------------------------
HANDLE_CHOICE = (
    ("keyname", "keyname"),
    ("external", "external"),
    ("uuid", "uuid"),
    ("md5", "md5"),
    # ("slugify", "slugify"),
    # ("count", "count"),
)

class DataClass(models.Model):

    keyname = models.SlugField(max_length=128, null=False, blank=False, unique=True)
    displayname = models.CharField(max_length=500,  null=True, blank=True)
    is_enabled = models.BooleanField(default=True)
    
    is_bigset = models.BooleanField(default=False)
    count_estimation = models.IntegerField(default=0)
    handle_method = models.CharField(choices=HANDLE_CHOICE, max_length=32, default="keyname")

    icon  = models.CharField('Icon', max_length=128, blank=True, default="")
    page = models.CharField(max_length=255,  null=True, blank=True)
    order = models.IntegerField(default=100)

    # CRUD permissions per class ; override global built-in ; apply to instances in that class
    p_create = models.CharField(max_length=256,  null=True, blank=True)
    p_read = models.CharField(max_length=256,  null=True, blank=True)
    p_update = models.CharField(max_length=256,  null=True, blank=True)
    p_delete = models.CharField(max_length=256,  null=True, blank=True)
    p_export = models.CharField(max_length=256,  null=True, blank=True)
    p_import = models.CharField(max_length=256,  null=True, blank=True)
    # no override  / all perms
    p_admin = models.CharField(max_length=256,  null=True, blank=True)

    class Meta:
        #db_table = "{{ app_name}}_category"
        ordering = ['keyname']
        verbose_name = "Cavaliba Data Class"
        verbose_name_plural = "Cavaliba Data Classes"

    def __str__(self):
        return f"{self.keyname}"



# ----------------------------------------------------------------------------------
# DataSchema
# ----------------------------------------------------------------------------------

# DataSchema
# - classobj FK => DataClass:keyname   "Site"
# - keyname: attribut Slug              "location", "address", "population", "notify_to", ...
# - displayname
# - format:  int, str, JSON, base64, date, static_list, user, group, DataClass, DataLink
# - format_ext:  (static_list keyname, DataClass keyname, DataLink keyname)
# - order (+page)
# - cardinal_min
# - cardinal_max
# [-widget, ...]



FIELD_FORMAT_CHOICE = (
    ("string", "string"),
    ("int", "int"),
    ("float", "float"),
    ("boolean", "boolean"),
    ("ipv4", "ipv4"),
    ("date", "date"),
    ("schema","schema"),
    ("group","group"),
    ("user","user"),
    ("datetime", "datetime"),
    ("json", "json"),
    ("text", "text"),
    ("enumerate", "enumerate"),
    ("external", "external"),

    # permission
    # html, yaml, json
    # bin / encrypt ?
    # password
    # file
    # link

)


class DataSchema(models.Model):

    classobj = models.ForeignKey("DataClass", on_delete=models.CASCADE)
    keyname = models.SlugField(max_length=128, null=False, blank=False)
    displayname = models.CharField(max_length=500,  null=True, blank=True)
    description = models.CharField(_("Description"), max_length=500, blank=True)
    is_enabled = models.BooleanField(default=True)

    dataformat = models.CharField(choices=FIELD_FORMAT_CHOICE, max_length=32, default="string")
    dataformat_ext = models.CharField(max_length=500,  null=True, blank=True)
    default_value = models.CharField(max_length=500,  null=True, blank=True, default="")

    page = models.CharField(max_length=255,  null=True, blank=True)
    order = models.IntegerField(default=100)

    cardinal_min = models.IntegerField(default=0)
    cardinal_max = models.IntegerField(default=1)

    # NEXT - CRUD permissions at field level
    ###p_create = models.CharField(max_length=256,  null=True, blank=True)
    #p_read = models.CharField(max_length=256,  null=True, blank=True)
    #p_update = models.CharField(max_length=256,  null=True, blank=True)
    ###p_delete = models.CharField(max_length=256,  null=True, blank=True)

    class Meta:
        #db_table = "{{ app_name}}_category"
        unique_together = ["classobj", "keyname"]
        ordering = ['classobj','keyname','order']
        verbose_name = "Cavaliba Data Schema"
        verbose_name_plural = "Cavaliba Data Schema"

    def __str__(self):
        return f"{self.classobj}:{self.keyname}({self.dataformat}/{self.dataformat_ext})"


# ----------------------------------------------------------------------------------
# DataInstance
# ----------------------------------------------------------------------------------
# DataInstance
# - classobj FK => DataClass:keyname   "Site"
# - keyname: slug                       "Site_X324C"
# - displayname                         "Site X2342C in Milan"
# - is_enabled
# - data: JSON => all attributs from Schema   
#     "Location:Paris",
#     "Address:XXXX",
#     "notify_to: ["group1","group2",...]
#     "X_hosts_app: [app1, app2, app3]",


class DataInstance(models.Model):

    classobj = models.ForeignKey("DataClass", on_delete=models.CASCADE)
    keyname = models.CharField(max_length=256, null=False, blank=False)
    handle = models.SlugField(max_length=128, null=True, blank=True)

    displayname = models.CharField(max_length=500,  null=True, blank=True)
    is_enabled = models.BooleanField(default=True)

    data_json = models.TextField(max_length=5000,  null=True, blank=True)
    # NEXT
    #remote_json = models.TextField(max_length=5000,  null=True, blank=True)
    #reverse_json = models.TextField(max_length=5000,  null=True, blank=True)
    
    # CRUD permissions per instance - override per-clas / built-in global
    #p_create = models.CharField(max_length=256,  null=True, blank=True)
    p_read = models.CharField(max_length=256,  null=True, blank=True)
    p_update = models.CharField(max_length=256,  null=True, blank=True)
    p_delete = models.CharField(max_length=256,  null=True, blank=True)

    last_update = models.DateTimeField(_("Last update"), auto_now_add=False, blank=True, null=True)

   
    
    class Meta:
        #db_table = "{{ app_name}}_category"
        indexes = [
            models.Index(fields=["classobj"]),
            models.Index(fields=["keyname"]),
            models.Index(fields=["is_enabled"]),
            ]
        unique_together = ["classobj", "keyname"]
        #unique_together = ["classobj", "handle"]
        ordering = ['classobj','keyname']
        verbose_name = "Cavaliba Data Instance"
        verbose_name_plural = "Cavaliba Data Instances"

    def __str__(self):
        if self.displayname:
            return f"{self.displayname}"
        else:
            return f"{self.keyname}"

source/app_data/forms.py
# (c) cavaliba.com - data - forms.py

from django import forms
from django.utils.translation import gettext as _


class DataUploadForm(forms.Form):

    file = forms.FileField(
        widget=forms.ClearableFileInput(attrs=None),
        #widget=forms.FileInput(attrs={'class': 'form-control-file'}),        
        label= _("File"),
        help_text = _("Choose a file (csv,yaml,json)"),
        )

source/app_data/templates/app_data/import.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_home/_navbar_app.html' %}
{% endblock %}

{% block title %}
<H2>{% translate 'Import Tool' %}</H2>
<hr>{% endblock %}

{% block content %}


<form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}

<div class="form-group">
<button type="submit" name="submit" value="verify" class="btn btn-secondary">{% translate 'Check' %}</button>
<button type="submit" name="submit" value="import" class="btn btn-danger">{% translate 'Import' %}</button>

<!-- <small class="form-text text-muted">{% translate 'Use Check button for YAML syntax check before import' %}</small> -->
</div>


<hr>
<h5>
  {% translate 'Choose a Pipeline (optional)' %}:
</h5>
<select class="form-select" aria-label="Default select example" name="pipeline">
  <option selected>-----------</option>
  {% for pipeline in pipelines %}<option value="{{ pipeline.keyname }}">{{ pipeline.displayname }}</option>
  {% endfor %}
</select>
<br>
<hr>

<H5>
  {% translate 'Choose a File ...' %}:
</H5>

<div class="input-group mb-3">
<input type="file" class="form-control" name="file"  aria-describedby="id_file_helptext" id="id_file">
<span class="btn btn-outline-secondary" id="id_clear">X</span>
</div>
<script>
    document.getElementById("id_clear").addEventListener("click", clearInput);
    function clearInput(){
        document.getElementById("id_file").value = "";
    }
</script>
<br>
<hr>

<h5>
  {% translate '... or paste YAML content below' %}: 
</h5>
<pre>
  <textarea class="form-control" name="rawdata" rows="16">{{ rawdata }}</textarea>
</pre>


</form>

  

{% endblock %}

source/app_data/templates/app_data/instance_detail.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_home/_navbar_app.html' %}
{% endblock %}


{% block title %}

<h2>
    <i class="fa fa-eye"></i>
    &nbsp; {{ classobj.displayname }} / {{ instance.displayname|default:instance.keyname }}
</h2>
<small class="text-muted">{{ instance.handle }} </small>
<hr>
{% endblock %}


{% block content %}
<form method="post" class="inline">{% csrf_token %}

<a class="btn btn-outline-dark" href="{% url 'app_data:instance_list' classobj.keyname %}" role="button">
    <i class="fa fa-backward" aria-hidden="true"></i>&nbsp; {% translate 'Back' %}</a>

{% if 'p_data_update' in aaa.perms %}
<a class="btn btn-outline-danger" 
        href="{% url 'app_data:instance_edit' classobj.keyname instance.handle|default:instance.keyname %}" role="button">
    <i class="fa fa-lg fa-pencil" aria-hidden="true"></i> &nbsp; {% translate 'Edit' %}</a>

<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#DeleteModal">
{% translate "Delete" %}
</button>
{% endif %}
</form>


<hr>


<table class="table table-hover table-bordered table-sm">

        <tr class="table-success"><td colspan="2">
            <strong>{{ classobj.displayname }} / {{ instance.keyname }}</strong></td></tr>

        <tr><td class="table-light" width="20%">{% translate 'Keyname(*)' %}</td>
        <td>{{ instance.keyname }}</td></tr>

        <tr><td class="table-light" width="20%">{% translate 'Handle' %}</td>
            <td>{{ instance.handle }}</td></tr>
    
        <tr><td class="table-light" width="20%">{% translate 'Display Name' %}</td>
        <td>{{ instance.displayname }}</td></tr>

        <tr><td class="table-light" width="20%">{% translate 'Is Enabled' %}</td>
        <td>{% if instance.is_enabled %}<i class="fa fa-check" aria-hidden="true"></i>{% endif %}
        </td></tr>

        <tr><td class="table-light" width="20%">{% translate 'Read Permission' %}</td>
            <td>{{ instance.p_read|default_if_none:'' }}</td></tr>

        <tr><td class="table-light" width="20%">{% translate 'Update Permission' %}</td>
            <td>{{ instance.p_update|default_if_none:'' }}</td></tr>

        <tr><td class="table-light" width="20%">{% translate 'Delete Permission' %}</td>
            <td>{{ instance.p_delete|default_if_none:'' }}</td></tr>

</table>


<hr>

{% for page,pageitems in instance.PAGES.items %}
<table class="table table-hover table-bordered table-sm">
    <tr class="table-primary">
        <td colspan="2">
            <strong>{{page}}</strong>
        </td>
    </tr>
    {%  for order,orderitems in pageitems.items %}{% for item in orderitems %}<tr>
    <td class="table-light" width="20%">
        {{ item.displayname }} 
    </td>
    <td>
        {% include 'app_data/fields/_datapoint_view_detail.html' %}
    </td>
    </tr>{% endfor %}{% endfor %}
</table>
{%  endfor %}





<!-- DELETE CONFIRM Modal -->
<div class="modal fade" id="DeleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">

<div class="modal-header">
<h1 class="modal-title fs-5" id="staticBackdropLabel">{% translate "Confirm delete ?" %}</h1>
<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
    
<div class="modal-body">
<p>{{ classobj.keyname }} :  {{ instance.keyname }} ?</p>
</div>

<div class="modal-footer">
<form action="{% url 'app_data:instance_delete' classobj.keyname instance.handle %}" method="post">{% csrf_token %}
<button role="button" class="btn btn-danger">{% translate "Delete" %}</button>
<a role="button" class="btn btn-outline-dark" data-bs-dismiss="modal">{% translate "Cancel" %}</a>
</form>
</div>

</div>
</div>
</div>



{% endblock %}

source/app_data/templates/app_data/instance_edit.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_home/_navbar_app.html' %}
{% endblock %}

{% block title %}
<h2>
  <i class="fa fa-pencil"></i>
  &nbsp; {{ classobj.displayname }} / {{ formular.displayname }} ({{formular.keyname}})
</h2>
<small class="text-muted">{{ formular.handle }} </small>
<hr>
{% endblock %}


{% block content %}
<form action="" method="post"> {% csrf_token %}

<a class="btn btn-outline-dark" href="{% url 'app_data:instance_list' classobj.keyname %}" role="button">
    <i class="fa fa-backward" aria-hidden="true"></i>&nbsp; {{ classobj.keyname }}</a>

{% if 'p_data_update' in aaa.perms %}
<input class="btn btn-danger" type="submit" name="save" value="{% translate 'Save' %}">
{% endif %}

<hr>

<!-- KEYNAME -->
<div class="mb-3 row">
  <label class="col-sm-2 col-form-label">{% translate 'Keyname(*)' %}</label>
  <div class="form-check col-sm-10">
   <input type="text" disabled class="form-control" name="keyname" value="{{ formular.keyname|default_if_none:''}}">
    <div class="form-text">Unique for this class - any chars</div>
  </div>
</div>

<!-- HANDLE -->
<div class="mb-3 row">
  <label class="col-sm-2 col-form-label">{% translate 'Handle' %}</label>
  <div class="form-check col-sm-10">
   <input type="text" disabled class="form-control" name="handle" value="{{ formular.handle|default_if_none:''}}">
    <div class="form-text">Unique for this class, no special char, no whitespace, no accent</div>
  </div>
</div>

<!-- DISPLAYNAME -->
<div class="mb-3 row">
<label class="col-form-label col-sm-2">{% translate 'Display Name' %}</label>
<div class="form-check col-sm-10">
<input type="text" class="form-control col-sm-10" name="displayname" value="{{ formular.displayname|default_if_none:''}}">
</div>
</div>

<!-- IS ENABLED -->
<div class="mb-3 row">
<label class="col-form-label col-sm-2">{% translate 'Is Enabled' %}</label>
<div class="col-sm-10 form-check">
<input class="form-check mt-2" type="checkbox" name="is_enabled"
  {% if formular.is_enabled %}checked{% endif %}> 
</div>
</div>

<!-- Permissions -->
{% if "p_permission_edit" in aaa.perms %}
<div class="mb-3 row">
  <label class="col-form-label col-sm-2"><b>{% translate 'Read Permission' %}</b></label>
  <div class="form-check col-sm-10">
  <input type="text" class="form-control col-sm-10" name="p_read" value="{{ formular.p_read|default_if_none:''}}">
  </div>
  </div>
<div class="mb-3 row">
  <label class="col-form-label col-sm-2"><b>{% translate 'Update Permission' %}</b></label>
  <div class="form-check col-sm-10">
  <input type="text" class="form-control col-sm-10" name="p_update" value="{{ formular.p_update|default_if_none:''}}">
  </div>
</div>
<div class="mb-3 row">
  <label class="col-form-label col-sm-2"><b>{% translate 'Delete Permission' %}</b></label>
  <div class="form-check col-sm-10">
  <input type="text" class="form-control col-sm-10" name="p_delete" value="{{ formular.p_delete|default_if_none:''}}">
  </div>
</div>
{% else %}
<div class="mb-3 row">
  <label class="col-form-label col-sm-2"><b>{% translate 'Read Permission' %}</b></label>
  <div class="form-check col-sm-10">
  <input disabled type="text" class="form-control col-sm-10" name="p_read" value="{{ formular.p_read|default_if_none:''}}">
  </div>
  </div>
<div class="mb-3 row">
  <label class="col-form-label col-sm-2"><b>{% translate 'Update Permission' %}</b></label>
  <div class="form-check col-sm-10">
  <input disabled type="text" class="form-control col-sm-10" name="p_update" value="{{ formular.p_update|default_if_none:''}}">
  </div>
</div>
<div class="mb-3 row">
  <label class="col-form-label col-sm-2"><b>{% translate 'Delete Permission' %}</b></label>
  <div class="form-check col-sm-10">
  <input disabled type="text" class="form-control col-sm-10" name="p_delete" value="{{ formular.p_delete|default_if_none:''}}">
  </div>
</div>
{% endif %}


<hr>

{% for page,pageitems in formular.PAGES.items %} <h4>{{ page }}</h4><hr>
{%  for order,orderitems in pageitems.items %}{% for item in orderitems %}
  {% if item.dataformat == "string" %}       {% include 'app_data/fields/_string.html' %}
{% elif item.dataformat == "int" %}          {% include 'app_data/fields/_int.html' %}
{% elif item.dataformat == "boolean" %}      {% include 'app_data/fields/_boolean.html' %}
{% elif item.dataformat == "schema" %}       {% include 'app_data/fields/_schema.html' %}
{% elif item.dataformat == "group" %}        {% include 'app_data/fields/_group.html' %}
{% elif item.dataformat == "ipv4" %}         {% include 'app_data/fields/_ipv4.html' %}
{% elif item.dataformat == "float" %}        {% include 'app_data/fields/_float.html' %}
{% elif item.dataformat == "date" %}         {% include 'app_data/fields/_date.html' %}
{% elif item.dataformat == "user" %}         {% include 'app_data/fields/_user.html' %}
{% elif item.dataformat == "text" %}         {% include 'app_data/fields/_text.html' %}
{% elif item.dataformat == "enumerate" %}    {% include 'app_data/fields/_enumerate.html' %}
{% elif item.dataformat == "external" %}  

{% else %} {% if item.is_multi %}
<div class="mb-3 row">
  <label class="col-form-label col-sm-2">{{ item.displayname }}</label>
  <div class="form-check col-sm-10">
  Unsupported Multi-value
  <div class="form-text">/!\UNKNOWN FORMAT {{item.dataformat }}</div>
</div>
</div>
{% else %}
<div class="mb-3 row">
  <label class="col-form-label col-sm-2">{{ item.displayname }}</label>
  <div class="form-check col-sm-10">
  <input type="text" class="form-control col-sm-10" 
       id="{{ item.fieldname }}" 
       name="{{ item.fieldname }}" 
       value="{{ item.value.0|default_if_none:''}}"
       >
  <div class="form-text">/!\ UNKNOWN FORMAT {{item.dataformat }}: {{ item.description }}</div>
</div>
</div>
{% endif %}{% endif %}{%  endfor %} <!-- internal item loop -->{%  endfor %} <!-- order loop -->{%  endfor %} <!-- page loop -->
</form>
{% endblock %}



{% block script %}<!-- select2 scripts -->
{% for page,pageitems in formular.PAGES.items %}{%  for order,orderitems in pageitems.items %}{% for item in orderitems %}

<!-- SCHEMA -->
{% if item.dataformat == "schema" %} 
    {% if item.bigset %}
    <script type="text/javascript">
    $('#id_{{ item.fieldname }}').select2({
      width: '100%',
      ajax: {
        //url: "https://api.github.com/search/repositories",
        url: "{% url 'app_data:ajax_instance' %}",
        dataType: 'json',
        delay: 250,
        cache: true,
        data: function (params) {
          return {
            q: params.term,
            c: '{{ item.dataformat_ext }}'
          };
        }
      },
      placeholder: '{% translate "Select items" %}'
      //minimumInputLength: 1
    });
    </script>

    {% else %}
    <script> 
      $(document).ready(function() {
        $('#id_{{ item.fieldname }}').select2({
          width: '100%'
      });
    });
    </script>
    {% endif %}

<!-- GROUP -->
{% elif item.dataformat == "group" %}
    <script> 
      $(document).ready(function() {
        $('#id_{{ item.fieldname }}').select2({
          width: '100%'
      });
    });
    </script>

<!-- USER -->
{% elif item.dataformat == "user" %}

    {% if item.bigset %}
    <script type="text/javascript">
    $('#id_{{ item.fieldname }}').select2({
      width: '100%',
      ajax: {
        //url: "https://api.github.com/search/repositories",
        url: "{% url 'app_user:ajax_user' %}",
        dataType: 'json',
        delay: 250,
        cache: true,
        data: function (params) {
          return {
            q: params.term
          };
        }
      },
      placeholder: '{% translate "Select users" %}'
      //minimumInputLength: 1
    });
    </script>

    {% else %}
    <script> 
      $(document).ready(function() {
        $('#id_{{ item.fieldname }}').select2({
          width: '90%'
      });
    });
    </script>
    {% endif %}



<!-- ENUMERATE -->
{% elif item.dataformat == "enumerate" %}
    <script> 
      $(document).ready(function() {
        $('#id_{{ item.fieldname }}').select2({
          width: '100%'
      });
    });
    </script>

{% endif %}

{% endfor %}{% endfor %}{% endfor %} {% endblock %}