source/app_home/urls.py
# (c) cavaliba.com - home - urls.py


from django.urls import path

from app_home import views

# url namespace
app_name="app_home"

urlpatterns = [

    # home/ >>  home/private/
    path('',  views.private, name='index'),
    path('private/', views.private, name='private'),

    # conf
    path('private/conf/', views.configuration, name='configuration'),
    path('private/conf/<slug:appname>/', views.configuration, name='configuration'),

    # logs
    path('private/log/', views.logview, name='log'),
    path('private/log/l/<str:level>/', views.logview, name='log'),
    path('private/log/purge/', views.logview, name='logpurge'),

]

source/app_sirene/urls.py
 # (c) cavaliba.com - sirene - urls.py

from django.urls import path

from . import public_views
from . import anonymous_views
from . import category_views
from . import publicpage_views
from . import template_views
from . import message_views

from . import configuration_views
from . import api_views
from . import sms_views




# url namespace
app_name="app_sirene"

urlpatterns = [

    # PUBLIC
    path('', public_views.index, name='index'),
    #path('', views_public.index, name='public'),

    # Anonymous / Trusted IPs / No AUTH
    path('anon/index/',  anonymous_views.list, name='anonymous'),
    path('anon/detail/<int:pageid>/', anonymous_views.detail, name='anonymous_detail'),

    # API
    path('api/', api_views.index, name='api_index'),

    # MESSAGE & EDITOR
    path('private/',                          message_views.list, name='private'),
    path('private/history/',                  message_views.history, name='history'),
    path('private/detail/<int:pageid>/',      message_views.detail, name='detail'),
    path('private/update/<int:mid>/',         message_views.update, name='message_update'),
    path('private/remove/',                   message_views.remove, name='message_remove'),
    path('private/editor2/',                  message_views.editor2, name='message_editor'),
    path('private/editor2/<int:template_id>/', message_views.editor2, name='message_editor'),


    # Configuration & Tools
    #path('private/config/', configuration_views.config, name='config'),
    path('private/doc/',    configuration_views.doc    , name='doc'),
    # path('private/email_test/', configuration_views.email_test, name='email_test'),
    # path('private/email_test/<int:userid>/', configuration_views.email_test, name='email_test'),
    path('private/flushall/', configuration_views.flushall, name='flushall'),
    #path('private/import/', configuration_views.conf_import, name='conf_import'),
    path('private/export/', configuration_views.conf_export, name='conf_export'),

    # SMS
    path('private/sms/send/', sms_views.sms_send, name='sms_send'),
    path('private/sms/stat/', sms_views.sms_stat, name='sms_stat'),
    path('private/sms/journal/', sms_views.sms_journal, name='sms_journal'),

    # Template / Predefined
    path('private/template/', template_views.list, name='template_list'),
    path('private/template/edit/', template_views.edit, name='template_edit'),
    path('private/template/edit/<int:tid>/', template_views.edit, name='template_edit'),
    path('private/template/delete/<int:tid>/', template_views.delete, name='template_delete'),
    path('private/template/selector/', template_views.selector, name='template_selector'),

    # PUBLIC PAGES
    path('private/publicpage/', publicpage_views.list, name='publicpage_list'),
    path('private/config/publicpage/edit/', publicpage_views.edit, name='publicpage_edit'),
    path('private/config/publicpage/edit/<int:ppid>/', publicpage_views.edit, name='publicpage_edit'),
    path('private/config/publicpage/delete/<int:ppid>/', publicpage_views.delete, name='publicpage_delete'),
    #
    path('private/publicpage/selector/', publicpage_views.selector, name='publicpage_selector'),
    path('private/publicpage/preview/<int:ppid>/', publicpage_views.preview, name='publicpage_preview'),
    path('private/publicpage/push/<int:ppid>/', publicpage_views.push, name='publicpage_push'),
#    path('private/publicpage/reset/', publicpage_views.reset, name='public_reset'),



    # CATEGORY
    path('private/category/', category_views.list, name='category_list'),
    path('private/category/edit/', category_views.edit, name='category_edit'),
    path('private/category/edit/<int:cid>/', category_views.edit, name='category_edit'),
    path('private/category/delete/<int:cid>/', category_views.delete, name='category_delete'),


]

source/app_user/urls.py
# (c) cavaliba.com - IAM - urls.py


from django.urls import path

from app_user import user_views
from app_user import group_views
from app_user import role_views
from app_user import ajax 


# url namespace
app_name="app_user"

urlpatterns = [

 
    # PRIVATE
    path('private/', user_views.private, name='private'),
    #path('private/list/', views.list, name='list'),
    #path('private/detail/<int:pageid>/', views.detail, name='detail'),
    path('private/debug/',  user_views.debug_env  , name='debug'),
    path('private/logout/', user_views.logout , name='logout'),

    # USER
    path('private/users/', user_views.list, name='user_list'),
    #path('private/users/import/', user_views.user_import, name='user_import'),
    path('private/user/detail/<int:userid>/', user_views.detail, name='user_detail'),
    path('private/user/detail/<str:login>/', user_views.detail, name='user_detail'),
    path('private/user/edit/', user_views.edit, name='user_edit'),
    path('private/user/edit/<int:userid>/', user_views.edit, name='user_edit'),
    path('private/user/edit/<str:login>/', user_views.edit, name='user_edit'),
    path('private/user/delete/<int:userid>/', user_views.delete, name='user_delete'),
    path('private/user/pref/', user_views.preferences, name='user_pref'),
    path('private/user/pref/<int:userid>/', user_views.preferences, name='user_pref'),
    path('private/user/email/test/<int:userid>/', user_views.email_test, name='email_test'),
    path('private/user/sms/test/<int:userid>/', user_views.sms_test, name='sms_test'),

    # groups
    path('private/groups/', group_views.list, name='group_list'),
    #path('private/groups/import/', group_views.group_import, name='group_import'),
    path('private/groups/edit/', group_views.edit, name='group_edit'),
    path('private/groups/edit/<int:gid>/', group_views.edit, name='group_edit'),
    path('private/groups/edit/<slug:keyname>/', group_views.edit, name='group_edit'),
    path('private/groups/detail/<int:gid>/', group_views.detail, name='group_detail'),
    path('private/groups/detail/<slug:gname>/', group_views.detail, name='group_detail'),
    path('private/groups/delete/<int:gid>/', group_views.delete, name='group_delete'),


    # roles
    path('private/roles/', role_views.list, name='role_list'),
    #path('private/roles/import/', role_views.role_import, name='role_import'),
    path('private/roles/edit/', role_views.edit, name='role_edit'),
    path('private/roles/edit/<int:gid>/', role_views.edit, name='role_edit'),
    path('private/roles/edit/<slug:keyname>/', role_views.edit, name='role_edit'),    
    path('private/roles/detail/<int:rid>/', role_views.detail, name='role_detail'),
    path('private/roles/detail/<slug:rname>/', role_views.detail, name='role_detail'),
    path('private/roles/delete/<int:gid>/', role_views.delete, name='role_delete'),

    # ajax 
    path('private/ajax/', ajax.ajax_user, name='ajax_user'),

    # api

]

source/core/urls.py
# (c) cavaliba.com - core urls.py

from django.urls import include, path
from django.shortcuts import render, redirect

import debug_toolbar

import app_sirene.public_views
import app_home.views

from django.contrib import admin

admin.site.site_header = 'CAVALIBA DB ADMIN'
admin.site.site_title = 'Cavaliba'
admin.site.site_name = "Cavaliba Admin Tools"


urlpatterns = [

    # /status/   => app_home status
    path('status/', app_home.views.status, name='status'),

    # /  >> /sirene/
    path('', app_sirene.public_views.index),

    # home/  >> app_home
    path('home/', include('app_home.urls')),

    # sirene/
    path('sirene/', include('app_sirene.urls')),
#    path('', include('app_sirene.urls')),

    # user/
    path('user/', include('app_user.urls')),

    # data
    path('data/', include('app_data.urls')),

    # local django auth 
    path("accounts/", include("django.contrib.auth.urls")),

    # django admin
    path('private/admin/', admin.site.urls),
    path('private/tinymce/', include('tinymce.urls')),
    

    path("private/__debug__/", include("debug_toolbar.urls")),

    # Deprecated:  OKTA login Init URI
    #path('private/', lambda request: redirect('app_sirene:private', permanent=False)),


]

source/app_home/models.py
# (c) cavaliba.com - home - models.py

from django.db import models
from django.utils.translation import gettext_lazy as _

from app_user.models import SirenePermission


# ---------------------------------------
# Dashboard
# ---------------------------------------

DASHBOARD_APP_STATE = (
     ("enabled", "enabled"),
     ("disabled", "disabled"),
     ("hidden", "hidden"),
)

class DashboardApp(models.Model):

    keyname   = models.SlugField('Key name(*)', max_length=100, blank=False, unique=True)
    displayname  = models.CharField('Display name', max_length=128, blank=True)
    description  = models.CharField('Description', max_length=500, blank=True)
    is_enabled  = models.BooleanField(_('Enabled'), default=True)
    url   = models.CharField('URL', max_length=1500, blank=True, default="")
    icon  = models.CharField('Icon', max_length=128, blank=True, default="")
    #page  = models.CharField('Page', max_length=128, blank=True, default="")
    sidebar_section  = models.CharField('Sidebar section', max_length=128, blank=True, default="")
    dashboard_section  = models.CharField('Dashboard section', max_length=128, blank=True, default="")
    order = models.IntegerField('Order', default=100)
    permission = models.ForeignKey(SirenePermission, null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = "app_home_dashboard_app"
        ordering = ['order']
        verbose_name = "Dashboard Application"
        verbose_name_plural = "Dashboard Applications"

    def __str__(self):
        return self.keyname


# ---------------------------------------
# Configuration
# ---------------------------------------

class CavalibaConfiguration(models.Model):

    appname = models.SlugField(_('Cavaliba App'), max_length=128, null=False, blank=False, default="home")
    keyname = models.SlugField(_('Keyname(*)'), max_length=128, null=False, blank=False)

    value   = models.CharField(_('Value'), max_length=1500, blank=True, null=True)

    description  = models.CharField(_('Description'), max_length=500,  null=True, blank=True)
    page    = models.CharField(_('Page'), max_length=1500, blank=True, default="")
    order   = models.IntegerField(_('Order'), default=100)

    # group
    # type : int/string/json/IP/...
    # default value ?

    class Meta:
        unique_together = ["appname", "keyname"]
        ordering = ['appname', 'page', 'order', 'keyname']
        verbose_name = "Cavaliba Configuration"
        verbose_name_plural = "Cavaliba Configurations"
        #unique_together = ('login', 'site',)


    def __str__(self):
        return self.keyname


# ---------------------------------------
# Logs
# ---------------------------------------

class CavalibaLog(models.Model):

    app = models.CharField(_('App'), max_length=200, blank=True, default="")
    view = models.CharField(_('View'), max_length=200, blank=True, default="")
    action = models.CharField(_('Action'), max_length=200, blank=True, default="")
    status = models.CharField(_('Status'), max_length=32, blank=True, default="")
    data = models.CharField(_('data'), max_length=2000, default="")
    
    level = models.CharField(_('Level'), max_length=20, default="na")
    created = models.DateTimeField(auto_now_add=True, db_index=True)   # , default=datetime.now
    
    #domain = models.CharField('Domain', max_length=200, default="na")
    
    username = models.CharField(_('Username'), max_length=256, default="na")
    user_ip = models.CharField(_('User IP'), max_length=64, default="")
    impersonate = models.CharField(_('Impersonate'), max_length=256, default="na")

    class Meta:
        #db_table = "{{ app_name}}_category"
        ordering = ['created']
        verbose_name = "Cavaliba Log"
        verbose_name_plural = "Cavaliba Logs"

    def __str__(self):
        return f"{self.created}/{self.username}({self.impersonate})/{self.user_ip} - {self.level}/{self.status} - {self.app}/{self.view}/{self.action}"


class CavalibaAPIStat(models.Model):

    keyname       = models.SlugField(_('Keyname'), max_length=128, unique=True)
    last_success = models.DateTimeField(_("Last success"), auto_now_add=False, blank=True, null=True)
    last_error   = models.DateTimeField(_("Last error"), auto_now_add=False, blank=True, null=True)
    success_count  = models.IntegerField(_("success count"), default=0)
    error_count  = models.IntegerField(_("Error count"), default=0)

    class Meta:
        verbose_name = "Cavaliba API Stat"
        verbose_name_plural = "Cavaliba API Stats"
        indexes = [
            models.Index(fields=["keyname"]),
            ]

    def __str__(self):
        return f"{self.keyname}"

source/app_home/templates/app_home/_navbar_app.html
{% load static %}
{% load i18n %}





{% for section in sidebar %}
<li class="sidebar-header">
    {{ section.0 }}
</li>

        {% for entry in section.1 %}
        <li class="sidebar-item">
            <a class="sidebar-link" href="{{ entry.url }}">
            <i class="fa {{ entry.icon }} fa-fw pe-2"></i>
            {{ entry.displayname }}
            </a>
        </li>
        {% endfor %}
{% endfor %}

source/app_home/templates/app_home/base.html
{% load static %}
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'v2/bootstrap533.min.css' %}" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'v2/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" /> --> 
<link rel="stylesheet" href="{% static 'v2/jquery.dataTables.css' %}">
<link rel="stylesheet" href="{% static 'v2/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'app_home/style.css' %}">
<title>{{ GLOBAL_APPNAME|default:"Cavaliba"}}</title>
<!-- <style>
#id_test_scope {
    color: #26b72b;
    width: 100%;
  }
</style> -->
</head>



<body>
  <div class="wrapper">

    <aside id="sidebar" class="js-sidebar"> <!-- SIDEBAR -->
        <div class="h-100">

              <div class="sidebar-logo">      
                  <a href="{% url 'app_home:private' %}">
                    {% if LOGO_SIZE > 0 %}<IMG src="/logo/logo.png" width="{{ LOGO_SIZE }}"></IMG>
                    {% else %}<i class="fa fa-lg fa-home fa-1x"></i>
                    {% endif %}
                    {{ GLOBAL_APPNAME|default:"Cavaliba" }}
                  </a>
              </div>
              <ul class="sidebar-nav">
                {% block navbar_app %}
                {% endblock %}
               </ul>

        </div>
    </aside>


    <!-- {% if 'p_doc_link' in aaa.perms %}
    <li class="nav-item px-1">
      <a class="nav-link" href="{% url 'app_sirene:doc' %}">
      <i class="fa fa-lg fa-book" aria-hidden="true"></i>&nbsp;Doc &nbsp;</a></li>
    {% endif %}
     -->



<!-- MAIN  -->

      <div class="main">

<!-- NAVBAR -->
          <nav class="navbar navbar-expand px-3 border-bottom">
              <button class="btn" id="sidebar-toggle" type="button">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse navbar">
                  <ul class="navbar-nav">
                      <li class="nav-item dropdown">
                          <a href="#" data-bs-toggle="dropdown" class="nav-icon pe-md-0 dropdown-toggle">
                            <i class="fa fa-user-o" aria-hidden="true"></i>&nbsp;
                            {{ aaa.username }} {% if aaa.is_admin %} (admin) {% endif %}
                          </a>
                          
                          <div class="dropdown-menu dropdown-menu-end">
          
                              {% if 'p_user_pref' in aaa.perms %}
                              <a href="{% url 'app_user:user_pref'  %}" class="dropdown-item">
                                <i class="fa fa-pencil fa-fw"></i>&nbsp; - &nbsp;{% translate 'Preferences' %}
                              </a>
                              {% endif %}

                              {% if 'p_user_debug' in aaa.perms %}
                              <a href="{% url 'app_user:debug' %}" class="dropdown-item">
                                <i class="fa fa-question fa-fw"></i>&nbsp; - &nbsp;
                                {% translate 'Debug' %}
                              </a>
                              {% endif %}

                              {% if aaa.is_admin %}
                              <a href="/private/admin/" class="dropdown-item">
                                <i class="fa fa-cog fa-fw"></i>&nbsp; - &nbsp;
                                {% translate 'DB Admin' %}
                              </a>
                              {% endif %}


                              <!-- LOGOUT -->
                              <a href="{% url 'app_user:logout' %}" class="dropdown-item">
                              <i class="fa fa-power-off fa-fw" aria-hidden="true"></i>&nbsp; - &nbsp;
                              {% translate 'Logout' %} {{ aaa.username }} {% if aaa.is_admin %} (admin){% endif %}
                              </a>

                          </div>
                      </li>
                  </ul>
              </div>
          </nav>

<!-- Content -->

          <main class="content px-3 py-2">

                <div class="container-fluid">

                  <!-- Messages Flash -->
                    {% if messages %}{% for message in messages %}
                    <div class="alert {{ message.tags }}  alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}{% endif %}
                  
                  
                  {% block title %}{% endblock %}
                  
                  {% block content %}{% endblock %}
                  
                </div>
          </main>

<!-- Footer -->
          <hr>
          <footer class="footer">
              <div class="container-fluid">
                  <div class="row text-muted">
                      <div class="col-6 text-start">
                          <p class="mb-0">
                              <a href="http://www.cavaliba.com/"" class="text-muted">
                                  <strong>(C) cavaliba.com - version {{ CAVALIBA_VERSION }} </strong>
                              </a>
                          </p>
                      </div>
                      <div class="col-6 text-end">
                          <ul class="list-inline">
                              <li class="list-inline-item">
                                  <a href="#" class="text-muted">Contact</a>
                              </li>
                              <li class="list-inline-item">
                                  <a href="#" class="text-muted">About Us</a>
                              </li>
                              <li class="list-inline-item">
                                  <a href="#" class="text-muted">Terms</a>
                          </ul>
                      </div>
                  </div>
              </div>
          </footer>

      </div>  <!-- main -->
  </div> <!-- WRAPPER -->

<!-- SCRIPTS -->

<script src="{% static 'v2/jquery.371.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'v2/bootstrap533.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'v2/htmx.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'v2/jquery.dataTables.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'v2/select2.min.js' %}"></script>
<script src="{% static 'tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'django_tinymce/init_tinymce.js' %}"></script>
<script src="{% static 'v2/sidebar.js' %}"></script>


<script>
  $(document).ready( function () {
    $('#table_managed').DataTable({
      "pageLength": 500,
      "autoWidth": false,
      order: [[0, 'asc']],
      "lengthMenu": [ [50, 500, 5000, -1], [50, 500, 5000, "Tous"] ],
      language: {
        processing:     "Traitement en cours...",
        search:         "Rechercher&nbsp;:",
        lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }

    })
   });
</script>
<script>
  $(document).ready( function () {
    $('#table_managed_rev').DataTable({
      "pageLength": 50,
      "autoWidth": false,
      order: [[0, 'desc']],
      "lengthMenu": [ [50, 500, 5000, -1], [50, 500, 5000, "Tous"] ],
      language: {
        processing:     "Traitement en cours...",
        search:         "Rechercher&nbsp;:",
        lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }

    })
   });
</script>
<script>

  $(document).ready( function () {
    $('#table_managed_sort').DataTable({
      "paging": false,
      "autoWidth": true,
      "searching": false,
      order: [[0, 'asc']],
      language: {
        processing:     "Traitement en cours...",
        search:         "Filter&nbsp;:",
        lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }

    })
   });
</script>

<script>
  $(document).ready( function () {
    $('#table_managed_search').DataTable({
      "paging": false,
      "autoWidth": true,
      "searching": true,
      order: [[0, 'asc']],
      language: {
        processing:     "Traitement en cours...",
        search:         "Filter&nbsp;:",
        lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }

    })
   });

</script>

{% block script %}{% endblock %}


</body>
</html>

source/app_home/templates/app_home/configuration.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_home/_navbar_app.html' %}
{% endblock %}

{% block title %}
{% if appname %}
<h3>{{ appname }}</h3>
<p class="text-muted">{% translate "Configuration" %}</p>
{% else %}<h3>Configuration</h3>
<p class="text-muted">{% translate 'Select application to configure' %}</p>
{% endif %}
{% endblock %}


{% block content %}
<hr>
<div class="d-inline-flex flex-nowrap bd-highlight">
{% for app in apps %}
<a class="btn btn-outline-dark me-2" href="{% url 'app_home:configuration' app %}">
{{ app.keyname }}
</a>
{% endfor %}  
</div>


{% if appname %}
<hr>

<form method="post">{% csrf_token %}
<input class="btn btn-danger me-2" type="submit" value="Enregistrer" name="save">
<hr>
<table class="table">
  {{ form.as_table }}
</table>
</form>
{% endif %}

{% endblock %}

source/app_home/templates/app_home/private.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_home/_navbar_app.html' %}
{% endblock %}


{% block content %}

{% for page in paginated %}
<hr>
<h5>{{ page.0 }}</h5>

<div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 row-cols-lg-6">
    
    {% for app in page.1 %}

        <div class="col py-1">

            {% if app.is_allowed %}<div class="card shadow">
            {% else %}<div class="card shadow-lg text-bg-secondary">{% endif %}

                <p class="text-center mb-1 pt-2"> <i class="fa {{ app.icon }} fa-2x"></i></p>
              
                {% if app.is_allowed %} 
                <small class="card-title text-center">{{ app.displayname }}</small>
                <A href="{{ app.url }}" class="stretched-link"></A>
                {% else %}<div class="card-title text-center"><em>{{ app.displayname }}</em></div>
                {% endif %}
            
            </div>
          </div>
    {% endfor %}
</div>

{% endfor %}

{% endblock %}