archive/3.14.0/django/app_sirene/urls.py
 # urls.py

from django.urls import path

from . import public_views
from . import anonymous_views
from . import category_views
from . import publicpage_views
from . import template_views
from . import message_views

from . import configuration_views
from . import api_views
from . import sms_views




# url namespace
app_name="app_sirene"

urlpatterns = [

    # PUBLIC
    path('', public_views.index, name='index'),
    #path('', views_public.index, name='public'),

    # Anonymous / Trusted IPs / No AUTH
    path('anon/index/',  anonymous_views.list, name='anonymous'),
    path('anon/detail/<int:pageid>/', anonymous_views.detail, name='anonymous_detail'),

    # API
    path('api/', api_views.index, name='api_index'),

    # MESSAGE & EDITOR
    path('private/',                          message_views.list, name='private'),
    path('private/history/',                  message_views.history, name='history'),
    path('private/detail/<int:pageid>/',      message_views.detail, name='detail'),
    path('private/update/<int:mid>/',         message_views.update, name='message_update'),
    path('private/remove/',                   message_views.remove, name='message_remove'),
    path('private/editor2/',                  message_views.editor2, name='message_editor'),
    path('private/editor2/<int:template_id>/', message_views.editor2, name='message_editor'),


    # Configuration & Tools
    #path('private/config/', configuration_views.config, name='config'),
    path('private/doc/',    configuration_views.doc    , name='doc'),
    # path('private/email_test/', configuration_views.email_test, name='email_test'),
    # path('private/email_test/<int:userid>/', configuration_views.email_test, name='email_test'),
    path('private/flushall/', configuration_views.flushall, name='flushall'),
    #path('private/import/', configuration_views.conf_import, name='conf_import'),
    path('private/export/', configuration_views.conf_export, name='conf_export'),

    # SMS
    path('private/sms/send/', sms_views.sms_send, name='sms_send'),
    path('private/sms/stat/', sms_views.sms_stat, name='sms_stat'),
    path('private/sms/journal/', sms_views.sms_journal, name='sms_journal'),

    # Template / Predefined
    path('private/template/', template_views.list, name='template_list'),
    path('private/template/edit/', template_views.edit, name='template_edit'),
    path('private/template/edit/<int:tid>/', template_views.edit, name='template_edit'),
    path('private/template/delete/<int:tid>/', template_views.delete, name='template_delete'),
    path('private/template/selector/', template_views.selector, name='template_selector'),

    # PUBLIC PAGES
    path('private/publicpage/', publicpage_views.list, name='publicpage_list'),
    path('private/config/publicpage/edit/', publicpage_views.edit, name='publicpage_edit'),
    path('private/config/publicpage/edit/<int:ppid>/', publicpage_views.edit, name='publicpage_edit'),
    path('private/config/publicpage/delete/<int:ppid>/', publicpage_views.delete, name='publicpage_delete'),
    #
    path('private/publicpage/selector/', publicpage_views.selector, name='publicpage_selector'),
    path('private/publicpage/preview/<int:ppid>/', publicpage_views.preview, name='publicpage_preview'),
    path('private/publicpage/push/<int:ppid>/', publicpage_views.push, name='publicpage_push'),
#    path('private/publicpage/reset/', publicpage_views.reset, name='public_reset'),



    # CATEGORY
    path('private/category/', category_views.list, name='category_list'),
    path('private/category/edit/', category_views.edit, name='category_edit'),
    path('private/category/edit/<int:cid>/', category_views.edit, name='category_edit'),
    path('private/category/delete/<int:cid>/', category_views.delete, name='category_delete'),


]

archive/3.14.0/django/core/urls.py
# (c) - cavaliba.com
# core urls.py

from django.urls import include, path
from django.shortcuts import render, redirect

import debug_toolbar

import app_sirene.public_views
import app_home.views

from django.contrib import admin

admin.site.site_header = 'CAVALIBA DB ADMIN'
admin.site.site_title = 'Cavaliba'
admin.site.site_name = "Cavaliba Admin Tools"


urlpatterns = [

    # /status/   => app_home status
    path('status/', app_home.views.status, name='status'),

    # /  >> /sirene/
    path('', app_sirene.public_views.index),

    # home/  >> app_home
    path('home/', include('app_home.urls')),

    # sirene/
    path('sirene/', include('app_sirene.urls')),
#    path('', include('app_sirene.urls')),

    # user/
    path('user/', include('app_user.urls')),

    # data
    path('data/', include('app_data.urls')),

    # local django auth 
    path("accounts/", include("django.contrib.auth.urls")),

    # django admin
    path('private/admin/', admin.site.urls),
    path('private/tinymce/', include('tinymce.urls')),
    

    path("private/__debug__/", include("debug_toolbar.urls")),

    # Deprecated:  OKTA login Init URI
    #path('private/', lambda request: redirect('app_sirene:private', permanent=False)),


]

archive/3.14.0/django/app_sirene/models.py
from django.db import models

#import datetime
from datetime import datetime
from datetime import timedelta
from django.utils import timezone
from django.utils.translation import gettext_lazy as _



from app_user.models import SireneUser
from app_user.models import SireneGroup

from app_data.models import DataClass
from app_data.models import DataInstance

# ---------------------------------------
# common
# ---------------------------------------


SIRENE_SEVERITY = (
     ("na", _("n/a")),                # white
     ("critical", _("critical")),     # black
     ("major", _("major")),           # red
     ("minor", _("minor")),           # yellow
     ("info", _("info")),             # blue
     ("other", _("other")),           # grey
     ("ok", _("ok")),                 # green
)



# ---------------------------------------
# Category
# ---------------------------------------

class Category(models.Model):
    """Message category"""

    name         = models.SlugField(_("Name"), max_length=128, blank=False, unique=True, default="na")
    longname     = models.CharField(_("Display name"), max_length=128, blank=True)
    description  = models.CharField(_("Description"), max_length=500, blank=True)
    is_enabled   = models.BooleanField(_("Enabled"), default=True)


    class Meta:
        ordering = ['id']
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.name}"


# ---------------------------------------
# PublicPages
# ---------------------------------------

class PublicPage(models.Model):

    name         = models.SlugField(_("Name"), max_length=128, blank=False, unique=True)
    title        = models.CharField(_('Title'), max_length=250, blank=True)
    body         = models.TextField(_('Text'), max_length=2500, blank=True)
    severity     = models.CharField(_('Severity'), choices=SIRENE_SEVERITY, max_length=20, default="na")
    is_default   = models.BooleanField(_('Default Public Page'), default=False)
    is_enabled   = models.BooleanField(_('Enabled'), default=True)

    class Meta:
        ordering = ['name']
        verbose_name = "Public Page"
        verbose_name_plural = "Public Pages"

    def __str__(self):
        return self.name


class PublicPageJournal(models.Model):

    name             = models.SlugField(_('Name'), max_length=128, blank=False)
    title            = models.CharField(_('Title'), max_length=250, blank=True)
    body             = models.TextField(('Text'), max_length=2500, blank=True)
    severity         = models.CharField(_('Severity'), choices=SIRENE_SEVERITY, max_length=20, default="na")
    is_default       = models.BooleanField(_('Default Public Page'), default=False)
    is_visible = models.BooleanField(_('Is visible'), default=True, db_index=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=False, db_index=True)   # , default=datetime.now
    created_by = models.CharField(_('Created by'), max_length=200, blank=True)
    removed_at = models.DateTimeField(_("Removed at"), auto_now_add=False, blank=True, null=True)
    removed_by = models.CharField(_('Removed by'), max_length=200, blank=True, default='auto')


    class Meta:
        ordering = ['name']
        verbose_name = "Public Page Journal"
        verbose_name_plural = "Public Pages Journal"

    def __str__(self):
        return "{} ({} - {})".format(self.name, self.severity, self.title )


    def remove(self, aaa=None):

        self.is_visible = False
        self.removed_at = timezone.now()
        if aaa:
            self.removed_by = aaa.get("username", "auto")
        else:
            self.removed_by = "auto"
        self.save()


    @classmethod
    def reset(cls, aaa=None):
        ''' remove all active public pages entries in the journal'''

        entries = cls.objects.filter(is_visible=True)
        for entry in entries:
            entry.remove(aaa)


    @classmethod
    def add(cls, publicpage=None, aaa=None):

        if not publicpage:
            return

        journal = cls()
        journal.name = publicpage.name
        journal.title = publicpage.title
        journal.body = publicpage.body
        journal.severity = publicpage.severity
        journal.is_default = publicpage.is_default
        journal.created_at = timezone.now()
        journal.created_by = aaa.get("username", "n/a")

        try:
            journal.save()
            return journal
        except Exception as e:
            return None



# ---------------------------------------
# Templates
# ---------------------------------------

class MessageTemplate(models.Model):

    name             = models.SlugField(_('Name'), max_length=128, blank=False, unique=True)
    category         = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    severity         = models.CharField(_('Severity'), choices=SIRENE_SEVERITY, max_length=20)
    is_enabled       = models.BooleanField(_('Enabled'), default=True)

    title            = models.CharField(_('Title'), max_length=250, blank=True)
    body             = models.TextField(_('Message'), max_length=5000, blank=True)
    description      = models.TextField(_('Description'), max_length=2500, blank=True)

    publicpage       = models.ForeignKey(PublicPage, null=True, blank=True, on_delete=models.SET_NULL)

    has_publicpage   = models.BooleanField(_('Public Page'), default=False)
    has_privatepage  = models.BooleanField(_('Private Page'), default=False)
    has_email        = models.BooleanField(_('Email'), default=False)
    has_sms          = models.BooleanField(_('SMS'), default=False)

    
    notify_site      = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_app       = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_sitegroup = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_customer  = models.ManyToManyField(DataInstance, related_name="+", blank=True)

    # additional groups
    notify_group     = models.ManyToManyField(SireneGroup, related_name="+", blank=True)
    


    class Meta:
        ordering = ['name']
        verbose_name = "MessageTemplate"
        verbose_name_plural = "MessageTemplates"

    def __str__(self):
        return "{} - {}".format(self.name, self.title )


# ---------------------------------------
# Messages 
# ---------------------------------------


class Message(models.Model):

    category         = models.CharField(_('Category'), max_length=128, default="?", blank=True) 
    severity         = models.CharField(_('Severity'), choices=SIRENE_SEVERITY, max_length=20, default="na")

    title            = models.CharField(_('Title'), max_length=250, blank=True)
    body             = models.TextField(_('Message'), max_length=5000, blank=True)

    publicpage_text  = models.TextField(_('Public page text'), max_length=2500, blank=True)
    publicpage       = models.ForeignKey(PublicPageJournal, null=True, blank=True, on_delete=models.SET_NULL)

    has_publicpage   = models.BooleanField(_('Private Page'), default=False)
    has_privatepage  = models.BooleanField(_('Private Page'), default=False)
    has_email        = models.BooleanField(_('Email'), default=False)
    has_sms          = models.BooleanField(_('SMS'), default=False)

    email_count = models.IntegerField(_('Emails sent'), default=0)
    sms_count = models.IntegerField(_('SMS sent'), default=0)

    is_visible = models.BooleanField(_('Visible'), default=True, db_index=True)
    
    template         = models.CharField(_('Template'), max_length=80, blank=True)

    created_at = models.DateTimeField(_('Created at'), auto_now_add=True, db_index=True)   # , default=datetime.now
    updated_at = models.DateTimeField(_('Updated at'), null=True, blank=True, db_index=True)
    removed_at = models.DateTimeField(_("Removed at"), auto_now_add=False, blank=True, null=True)

    created_by = models.CharField(_('Created by'), max_length=200, blank=True)
    updated_by = models.CharField(_('Updated by'), max_length=200, blank=True)
    removed_by = models.CharField(_('Removed by'), max_length=200, blank=True)

    # for MessageUpdate new notifications
    notify_customer  = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_site      = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_app       = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_sitegroup = models.ManyToManyField(DataInstance, related_name="+", blank=True)
    notify_group     = models.ManyToManyField(SireneGroup, related_name="+", blank=True)
    
    # auto populated
    notify_text      = models.TextField(_('Message (text)'), blank=True)
    # individual users notified
    users            = models.ManyToManyField(SireneUser, related_name="+", blank=True)
    users_text       = models.TextField(_('Users (text)'), blank=True)

    class Meta:
        ordering = ['created_at','severity']
        verbose_name = "Message"
        verbose_name_plural = "Messages"


    def __str__(self):
        return "{} - {} - {}".format(self.title, self.category, self.severity )


    def remove(self, aaa=None):

        self.is_visible = False
        self.removed_at = timezone.now()
        if aaa:
            self.removed_by = aaa.get("username", "auto")
        else:
            self.removed_by = "auto"
        self.save()

        # also remove associated PublicPageJournal entry
        if self.publicpage:
            self.publicpage.remove(aaa=aaa)


class MessageUpdate(models.Model):

    message    = models.ForeignKey(Message, related_name="updates", on_delete=models.CASCADE)
    content    = models.TextField(_('Message'), max_length=5000, blank=True)
    created_at = models.DateTimeField(_('created at'), auto_now_add=True, db_index=True)   # , default=datetime.now

archive/3.14.0/django/app_sirene/templates/app_sirene/_navbar_app.html
{% load static %}
{% load i18n %}



<li class="sidebar-header-active">
  {{ SIRENE_APPNAME|default:"Sirene!"}}
</li>

<!-- Consult -->
<li class="sidebar-header">
  {% translate 'Messages' %}
</li>


{% if 'p_sirene_access' in aaa.perms %}
<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:private' %}">
  <i class="fa fa-fw fa-vcard"></i>&nbsp; - &nbsp;
  {% translate 'Private view' %}    </a>
</li>
{% endif %}

<li class="sidebar-item">
  <a class="sidebar-link" href="/?public=yes">
  <i class="fa fa-fw fa-globe"></i>&nbsp; - &nbsp;
  {% translate 'Public view' %}
  </a>
</li>


{% if 'p_sirene_history' in aaa.perms %}
<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:history' %}">
  <i class="fa fa-fw fa-book"></i>&nbsp; - &nbsp;
  {% translate 'History' %}
</a>
</li>
{% endif %}

<!-- NEW -->
<li class="sidebar-header">
  {% translate 'New notification' %}
</li>


{% if 'p_sirene_new' in aaa.perms %}
<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:template_selector' %}">
  <i class="fa fa-fw fa-bullhorn" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'From Template' %}
</a>
</li>

<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:message_editor' %}">
  <i class="fa fa-fw fa-pencil" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'Empty form' %}
</a>
</li>

         
<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:publicpage_selector' %}">
  <i class="fa fa-fw fa-globe" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'Public Pageonly' %}
</a>
</li>

<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:sms_send' %}">
  <i class="fa fa-fw fa-mobile" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'Send a SMS' %}
</a>
</li>

<!-- Config -->
<li class="sidebar-header">
  {% translate 'Configuration' %}
</li>

<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:template_list' %}">
  <i class="fa fa-fw fa-mobile" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'Manage Templates' %}
</a>
</li>

<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:publicpage_list' %}">
  <i class="fa fa-fw fa-globe" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'Manage Public Pages' %}
</a>
</li>

<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_sirene:category_list' %}">
  <i class="fa fa-fw fa-tag" aria-hidden="true"></i>&nbsp; - &nbsp;
  {% translate 'Manage Categories' %}
</a>
</li>

<!-- Special -->
<li class="sidebar-header">
  {% translate 'Special' %}
</li>

<!-- Flushall -->      
{% if 'p_sirene_flushall' in aaa.perms %}
<li class="nav-item px-5">
  <form class="form-inline" action="{% url 'app_sirene:flushall' %}" method="post">{% csrf_token %}
    <input class="btn btn-outline-danger mx-2" type="submit" value="{% translate 'Archive all' %}" name="save">
  </form>
</li>
{% endif %}



{% endif %}

archive/3.14.0/django/app_sirene/templates/app_sirene/_pub_critical.html
{% load static %}
{% load i18n %}
 
 <!-- critical -->

<div class="mt-4 p-3 bg-{{ page.bgcolor|default:'success' }} {{ page.fgcolor|default:'text-white' }} ">

  <h3>{{ page.title }}</h3>
  <hr class="my-4">
  <span style="white-space: pre-wrap;">{{ page.body | safe}}</span>
  
  {% if page.created_at %}
  <hr class="my-4">
  <em>
  <div>{% translate 'Created' %} : {{ page.created_at |date:'Y-m-d H:i:s' }}</div>
  </em>
  {% endif %}

{% if aaa.is_trusted_ip or aaa.is_visitor or aaa.is_authenticated %}
	<hr>
	<a class="btn btn-outline-light mr-3" href="{% url 'app_sirene:anonymous' %}" role="button">
	<i class="fa fa-plus" aria-hidden="true"></i> Détails</a>
	{% endif %}

</div>

archive/3.14.0/django/app_sirene/templates/app_sirene/_pub_info.html
{% load static %}
{% load i18n %}
 
 <!-- info -->

<div class="mt-4 p-3 bg-{{ page.bgcolor|default:'success' }} {{ page.fgcolor|default:'text-white' }} ">

  <h3>{{ page.title }}</h3>
  <hr class="my-4">
  <span style="white-space: pre-wrap;">{{ page.body | safe}}</span>
  
  {% if page.created_at %}
  <hr class="my-4">
  <em>
  <div>{% translate 'Created' %} : {{ page.created_at |date:'Y-m-d H:i:s' }}</div>
  </em>
  {% endif %}

{% if aaa.is_trusted_ip or aaa.is_visitor or aaa.is_authenticated %}
	<hr>
	<a class="btn btn-outline-light mr-3" href="{% url 'app_sirene:anonymous' %}" role="button">
	<i class="fa fa-plus" aria-hidden="true"></i> Détails</a>
	{% endif %}

</div>

archive/3.14.0/django/app_sirene/templates/app_sirene/conf_export.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_sirene/_navbar_app.html' %}
{% endblock %}

{% block title %}
<H2>{% translate 'Configuration Export' %}</H2>
<hr>{% endblock %}

{% block content %}

<pre>
{{ rawdata }}
</pre>


</form>

{% endblock %}

archive/3.14.0/django/app_sirene/templates/app_sirene/message_detail.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_sirene/_navbar_app.html' %}
{% endblock %}

{% block title %}
<H2>
{% if not page.is_visible %}<span class="badge text-bg-secondary">{% translate 'HISTORY' %}</span>{% endif %}
{{ page.title }}</H2>
<hr>{% endblock %}

{% block content %}

{% if page.is_visible %}

	{% if 'p_sirene_update' in aaa.perms %}		
		<a class="btn btn-outline-primary" href="{% url 'app_sirene:message_update' page.id %}" role="button">
		<i class="fa fa-pencil"></i>
		{% translate 'Post an Update' %}
		</a>
	{% endif %}

	{% if 'p_sirene_archive' in aaa.perms %}
		<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#confirmModal_archive">
		<i class="fa fa-trash" aria-hidden="true"></i>
		{% translate 'To History' %}
		</button>
	{% endif %}

<hr>
{% endif %}



<h4><span class="badge text-bg-{{ page.bgcolor }}">
{{ page.category }} - {% translate page.severity %}</span></h4>



{% if page.body %}
<p><b>{% translate 'Initial message on' %} {{ page.created_at }} ({{ page.created_by }})</b></p>
<div class="border border-secondary rounded" style='background-color:#fff'>
<div class="mx-3 my-3">
{{ page.body | safe}}
</div>
</div>
{% endif %}

{% for upd in page.updates.all %}
<br>
<p><b>{% translate 'Updated on ' %} {{ upd.created_at }} ({{ upd.created_by }})</b></p>
<div class="border border-secondary rounded" style='background-color:#eee'>
<div class="mx-3 my-3">
{{ upd.content|safe}}
</div>
</div>
{% endfor %}

<hr>
<table class="table small table-striped table-hover table-sm">
	<tr><th>{% translate 'Message ID' %}</th><td>{{ page.id }}</td></tr>
	<tr><th>{% translate 'Title' %}</th><td>{{ page.title }}</td></tr>
	<tr><th>{% translate 'Created' %} ({% translate 'date' %})</th><td>{{ page.created_at|date:'Y-m-d H:i:s (D)' }}</td></tr>
	<tr><th>{% translate 'Created' %} ({% translate 'author' %})</th><td>{{ page.created_by }}</td></tr>
	<tr><th>{% translate 'Updated' %} ({% translate 'date' %})</th><td>{{ page.updated_at|date:'Y-m-d H:i:s (D)' }}</td></tr>
	<tr><th>{% translate 'Updated' %} ({% translate 'author' %})</th><td> {{ page.updated_by }}</td></tr>
	<tr><th>{% translate 'Removed' %} ({% translate 'date' %})</th><td>{{ page.removed_at|date:'Y-m-d H:i:s (D)' }}</td></tr>
	<tr><th>{% translate 'Removed' %} ({% translate 'author' %})</th><td>{{ page.removed_by }}</td></tr>
	<tr><th>{% translate 'Public Page' %}</th><td>{{ page.publicpage|default:"n/a" }}</td></tr>

	{% if page.has_email %}
	<tr><th>{% translate 'Email' %}</th><td>{{ page.email_count }}</td></tr>
	{% else %}<tr><th>{% translate 'Email' %}</th><td>{% translate 'No' %}</td></tr>
	{% endif %}

	{% if page.has_sms %}
	<tr><th>{% translate 'SMS' %}</th><td>{{ page.sms_count  }}</td></tr>
	{% else %}
	<tr><th>SMS</th><td>{% translate 'No' %}</td></tr>
	{% endif %}

	<tr><th>{% translate 'To' %} ({% translate 'email/sms' %})</th><td>{{ page.notify_text }}</td></tr>
	
	<tr><th>{% translate 'Template' %}</th><td>{{ page.template|default:"n/a" }}</td></tr>
	


</table>


<!-- Remove CONFIRM Modal -->
{% if 'p_sirene_archive' in aaa.perms %}
<div class="modal fade" id="confirmModal_archive" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
<div class="modal-dialog">
<div class="modal-content">

<div class="modal-header">
<h1 class="modal-title fs-5" id="staticBackdropLabel">{% translate "Send to history ?" %}</h1>
<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
    
      <div class="modal-body">
        <p class="h4">{% translate 'Title' %}: {{ page.title|default:'n/a' }}</p>
       	<p>{% translate 'Created' %}: {{ page.created_at|date:'Y-m-d H:i:s' }} / {{ page.created_by }}</p>
 				<p><span class="badge text-bg-{{ page.bgcolor }}">{{ page.category }} - {% translate page.severity %} </span></p>
      </div>

<div class="modal-footer">
<form action="{% url 'app_sirene:message_remove' %}" method="post">{% csrf_token %}
<input type="hidden" class=".mypageid" id="pageid" name="pageid" value="{{page.id}}" />
<button role="button" class="btn btn-danger">{% translate "To History" %}</button>
<a role="button" class="btn btn-outline-dark" data-bs-dismiss="modal">{% translate "Cancel" %}</a>
</form>
</div>

</div>
</div>
</div>




{% endif %}


{% endblock %}

archive/3.14.0/django/app_sirene/templates/app_sirene/message_edit.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_sirene/_navbar_app.html' %}
{% endblock %}

{% block title %}<H2><i class="fa fa-fw fa-bullhorn" aria-hidden="true"></i>&nbsp;
{% if form.title.value %}{{ form.title.value }}{% else %}
{% translate 'New message' %}{% endif %}</H2>
<hr>{% endblock %}

{% block content %}


<form action="" method="post"> {% csrf_token %}
<input type="hidden" id="postId" name="name" value="{{ form.name }}">

<a class="btn btn-outline-dark" onclick="history.back()" role="button">
 <i class="fa fa-backward" aria-hidden="true"></i>&nbsp;{% translate 'Back' %}</a>

<input class="btn btn-danger" type="submit" value="{% translate 'Send' %}">



<br>
<!-- Description / Usage -->
{% if form.description %}
<hr>
<div class="alert alert-warning" role="alert">
<pre><b>{% translate 'Usage' %}</b>

{{ form.description.value }}</pre>
</div>
<hr>
{% endif %}


<!-- FORM-->
<table class="table">
{{ form.as_table }}
</table>


<!-- Butons bottom -->
<div class="form-group">
<a class="btn btn-outline-dark" onclick="history.back()" role="button">
   <i class="fa fa-backward" aria-hidden="true"></i>&nbsp;Retour </a>
<button type="submit" class="btn btn-danger">Publier</button>
</div>

</form>
{% endblock %}


<!-- activate select2 on specified fields  -->
{% block script %}
<script>
$(document).ready(function() { $('#id_notify_group').select2({ width: '100%' }); });
$(document).ready(function() { $('#id_notify_sitegroup').select2({ width: '100%' }); });
$(document).ready(function() { $('#id_notify_app').select2({ width: '100%' }); });
$(document).ready(function() { $('#id_notify_site').select2({ width: '100%' }); });
$(document).ready(function() { $('#id_notify_customer').select2({ width: '100%' }); });
</script>
{% endblock %}