archive/3.14.0/django/app_user/urls.py
# app_user - urls.py
# (c) cavaliba.com 


from django.urls import path

from app_user import user_views
from app_user import group_views
from app_user import role_views
from app_user import ajax 


# url namespace
app_name="app_user"

urlpatterns = [

 
    # PRIVATE
    path('private/', user_views.private, name='private'),
    #path('private/list/', views.list, name='list'),
    #path('private/detail/<int:pageid>/', views.detail, name='detail'),
    path('private/debug/',  user_views.debug_env  , name='debug'),
    path('private/logout/', user_views.logout , name='logout'),

    # USER
    path('private/users/', user_views.list, name='user_list'),
    #path('private/users/import/', user_views.user_import, name='user_import'),
    path('private/user/detail/<int:userid>/', user_views.detail, name='user_detail'),
    path('private/user/detail/<str:login>/', user_views.detail, name='user_detail'),
    path('private/user/edit/', user_views.edit, name='user_edit'),
    path('private/user/edit/<int:userid>/', user_views.edit, name='user_edit'),
    path('private/user/edit/<str:login>/', user_views.edit, name='user_edit'),
    path('private/user/delete/<int:userid>/', user_views.delete, name='user_delete'),
    path('private/user/pref/', user_views.preferences, name='user_pref'),
    path('private/user/pref/<int:userid>/', user_views.preferences, name='user_pref'),
    path('private/user/email/test/<int:userid>/', user_views.email_test, name='email_test'),
    path('private/user/sms/test/<int:userid>/', user_views.sms_test, name='sms_test'),

    # groups
    path('private/groups/', group_views.list, name='group_list'),
    #path('private/groups/import/', group_views.group_import, name='group_import'),
    path('private/groups/edit/', group_views.edit, name='group_edit'),
    path('private/groups/edit/<int:gid>/', group_views.edit, name='group_edit'),
    path('private/groups/edit/<slug:keyname>/', group_views.edit, name='group_edit'),
    path('private/groups/detail/<int:gid>/', group_views.detail, name='group_detail'),
    path('private/groups/detail/<slug:gname>/', group_views.detail, name='group_detail'),
    path('private/groups/delete/<int:gid>/', group_views.delete, name='group_delete'),


    # roles
    path('private/roles/', role_views.list, name='role_list'),
    #path('private/roles/import/', role_views.role_import, name='role_import'),
    path('private/roles/edit/', role_views.edit, name='role_edit'),
    path('private/roles/edit/<int:gid>/', role_views.edit, name='role_edit'),
    path('private/roles/edit/<slug:keyname>/', role_views.edit, name='role_edit'),    
    path('private/roles/detail/<int:rid>/', role_views.detail, name='role_detail'),
    path('private/roles/detail/<slug:rname>/', role_views.detail, name='role_detail'),
    path('private/roles/delete/<int:gid>/', role_views.delete, name='role_delete'),

    # ajax 
    path('private/ajax/', ajax.ajax_user, name='ajax_user'),

    # api

]

archive/3.14.0/django/core/urls.py
# (c) - cavaliba.com
# core urls.py

from django.urls import include, path
from django.shortcuts import render, redirect

import debug_toolbar

import app_sirene.public_views
import app_home.views

from django.contrib import admin

admin.site.site_header = 'CAVALIBA DB ADMIN'
admin.site.site_title = 'Cavaliba'
admin.site.site_name = "Cavaliba Admin Tools"


urlpatterns = [

    # /status/   => app_home status
    path('status/', app_home.views.status, name='status'),

    # /  >> /sirene/
    path('', app_sirene.public_views.index),

    # home/  >> app_home
    path('home/', include('app_home.urls')),

    # sirene/
    path('sirene/', include('app_sirene.urls')),
#    path('', include('app_sirene.urls')),

    # user/
    path('user/', include('app_user.urls')),

    # data
    path('data/', include('app_data.urls')),

    # local django auth 
    path("accounts/", include("django.contrib.auth.urls")),

    # django admin
    path('private/admin/', admin.site.urls),
    path('private/tinymce/', include('tinymce.urls')),
    

    path("private/__debug__/", include("debug_toolbar.urls")),

    # Deprecated:  OKTA login Init URI
    #path('private/', lambda request: redirect('app_sirene:private', permanent=False)),


]

archive/3.14.0/django/app_user/models.py
# app_user - models.py

from django.db import models

#import datetime
from datetime import datetime
from datetime import timedelta
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# ---------------------------------------
# SireneUser
# ---------------------------------------



class SireneUser(models.Model):

    login  = models.CharField(_('Login/Identifier(*)'), max_length=128, unique=True, blank=False)
    external_id = models.CharField(_('External ID'), max_length=128, null=True, blank=True) 

    email = models.CharField(_('Email'), max_length=128, null=True, blank=True)
    mobile = models.CharField(_('Mobile'), max_length=32, null=True, blank=True)
    firstname = models.CharField(_('Firstname'), max_length=128, null=True, blank=True)
    lastname = models.CharField(_('Lastname'), max_length=128, null=True, blank=True)
    displayname = models.CharField(_("Display name"), max_length=500,  null=True, blank=True)

    description = models.CharField(_('Description'), max_length=500, null=True, blank=True)
    is_enabled = models.BooleanField(_('Enabled'), default=True)
    last_login = models.DateTimeField(_("Last Login"), auto_now_add=False, blank=True, null=True)

    # Sirene Prefs 
    want_notifications = models.BooleanField(_('Want Notifications'), default=True)
    want_24 = models.BooleanField(_('Want 24/24'), default=True)
    want_sms = models.BooleanField(_('Want SMS'), default=False)
    want_email = models.BooleanField(_('Want Email'), default=True)
    secondary_email  = models.CharField(_('Secondary Email'), max_length=128, null=True, blank=True)
    secondary_mobile  = models.CharField(_('Secondary Mobile'), max_length=128, null=True, blank=True)

    last_update = models.DateTimeField(_("Last update"), auto_now_add=False, blank=True, null=True)


    class Meta:
        ordering = ['login']
        verbose_name = "Sirene User"
        verbose_name_plural = "Sirene Users"
        #unique_together = ('login', 'site',)
        indexes = [
            models.Index(fields=["login"]),
            models.Index(fields=["is_enabled"]),
            models.Index(fields=["displayname"]),
            models.Index(fields=["email"]),
            ]


    def __str__(self):
        if self.displayname:
            return "{} - {}".format(self.login ,self.displayname )
        else:
            return "{}".format(self.login)


# ---------------------------------------
# SireneGroup & Role
# ---------------------------------------

class SireneGroup(models.Model):
    keyname      = models.SlugField(_('Keyname(*)'), max_length=128, blank=False, unique=True,)
    displayname  = models.CharField(_("Display name"), max_length=500,  null=True, blank=True)
    description  = models.CharField(_('Description'), max_length=500,  null=True, blank=True)
    is_enabled   = models.BooleanField(_('Enabled'), default=True)
    is_role      = models.BooleanField(_('Role'), default=False)
    is_builtin   = models.BooleanField(_('Built-in group'), default=False)
    users        = models.ManyToManyField(SireneUser, blank=True)
    subgroups    = models.ManyToManyField('self', symmetrical=False, blank=True)
    #roles        = models.ManyToManyField('SireneRole', blank=True)
    permissions  = models.ManyToManyField('SirenePermission', blank=True)

    last_update = models.DateTimeField(_("Last update"), auto_now_add=False, blank=True, null=True)


    class Meta:
        ordering = ['keyname']
        verbose_name = "Sirene Group"
        verbose_name_plural = "Sirene Groups"
        indexes = [
            models.Index(fields=["keyname"]),
            models.Index(fields=["is_enabled"]),
            models.Index(fields=["is_role"]),
            ]

    def __str__(self):
        return "{}".format(self.keyname )


# RBAC
# -------------------------
# SireneUser => SireneGroup (0..N)  =>  || => SireneRole (0..N) <= SirenePermission
# Roles are provided by each app (or global if app is Null)
# Roles are set of granular Permissions
# granular / atomic permission provided by each app
# p_xxx_permision[_c|_r|_u|_d|...]
# ex. p_home_access

class SirenePermission(models.Model):

    keyname     = models.SlugField(_('Permission(*)'), max_length=128, blank=False, unique=True )
    appname     = models.SlugField(_('Sirene App'), max_length=128, null=True, blank=True )
    displayname = models.CharField(_("Display name"), max_length=500,  null=True, blank=True)
    description = models.CharField('Description', max_length=500,  null=True, blank=True)
    is_builtin  = models.BooleanField(_('Built-in permission'), default=False)
    default     = models.BooleanField(_('Allowed by default'), default=False)


    class Meta:
        ordering = ['keyname']
        verbose_name = "Sirene Permission"
        verbose_name_plural = "Sirene Permissions"
        indexes = [
            models.Index(fields=["keyname"]),
            models.Index(fields=["appname"]),
            ]


    def __str__(self):
        return f"{self.keyname}"


# -----------------------------------------------------------------------------
# Sirene Visitor
# ------------------------------------------------------------------------------
class SireneVisitor(models.Model):

    username   = models.CharField(_('Username'), max_length=255, unique=True, blank=False)
    user_ip    = models.CharField(_('Visitor IP'), max_length=64, default="")
    last_login = models.DateTimeField("Last Login", auto_now_add=False, blank=True, null=True)


    class Meta:
        ordering = ['last_login']
        verbose_name = "Sirene Visitor"
        verbose_name_plural = "Sirene Visitors"
        indexes = [
            models.Index(fields=["username"]),
            ]


    def __str__(self):
        return self.username

archive/3.14.0/django/app_user/templates/app_user/_navbar_app.html
{% load static %}
{% load i18n %}


<li class="sidebar-header-active">
  {% translate 'Identités' %}
</li>


<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_user:user_list' %}">
    <i class="fa fa-fw fa-lg fa-user" aria-hidden="true"></i>
      {% translate 'Users' %}
  </a>
</li>

<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_user:group_list' %}">
    <i class="fa fa-fw fa-lg fa-users" aria-hidden="true"></i>
    {% translate 'Groups' %}
  </a>
</li>


<li class="sidebar-item">
  <a class="sidebar-link" href="{% url 'app_user:role_list' %}">
    <i class="fa fa-fw fa-lg fa-user-secret" aria-hidden="true"></i>
    {% translate 'Roles' %}
  </a>
</li>

archive/3.14.0/django/app_user/templates/app_user/group_detail.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_user/_navbar_app.html' %}
{% endblock %}

{% block title %}
<h3>{{ group.displayname|default:group.keyname }}</h3>
<small class="text-muted">{% translate "Group details" %}</small>
<hr>{% endblock %}

{% block content %}

<!-- TOOLS  -->
<a class="btn btn-outline-dark" href="{% url 'app_user:group_list' %}" role="button">
<i class="fa fa-backward" aria-hidden="true"></i>&nbsp;{% translate "Back" %} </a>

{% if 'p_group_update' in aaa.perms %}
  <a class="btn btn-success" href="{% url 'app_user:group_edit' group.id %}" role="button">
  {% translate 'Edit' %}</a>
{% endif %}

{% if 'p_group_delete' in aaa.perms %}
  {% if not group.is_builtin %}
  <a type="button" class="btn btn-danger float-right" data-bs-toggle="modal" data-bs-target="#DeleteModal">
    {% translate "Delete" %}
  </a>
  {% endif %}
{% endif %}

<hr>

<table class="table table-hover table-bordered table-sm">

  <tr class="table-success"><td colspan="2"><strong>{% translate 'Group' %}</strong></td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Keyname(*)' %}</td>
  <td>{{ group.keyname }}</td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Display Name' %}</td>
  <td>{{ group.displayname }}</td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Is Enabled' %}</td>
  <td>{% if group.is_enabled %}<input type="checkbox" checked disabled/>
      {% else %}<input type="checkbox" disabled/>{% endif %}
  </td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Built-in' %}</td>
  <td>{% if group.is_builtin %}<input type="checkbox" checked disabled/>
      {% else %}<input type="checkbox" disabled/>{% endif %}
  </td></tr>

</table>

<hr>

<!-- USERS -->
<table class="table table-hover table-bordered table-sm">
<tr class="table-primary"><td colspan="4"><strong>{% translate 'Users' %}</strong></td></tr>
<tr>
<td class="table-light">
    <div class="d-flex flex-wrap"> 
    {% for z in group.users.all %}
    <a class="btn btn-primary btn-sm mx-1 my-1" href="{% url 'app_user:user_detail' z.login %}" role="button">
    {{ z.login }}</a>{% endfor %}     
    {% for z in users_indirect %}
    <a class="btn btn-outline-primary btn-sm mx-1 my-1" href="{% url 'app_user:user_detail' z.login %}" role="button">
    {{ z.login }}</a>{% endfor %}     
    </div>    
</td></tr>
</table>


<!-- SUBGROUPS -->
<table class="table table-hover table-bordered table-sm">
<tr class="table-success"><td colspan="4"><strong>{% translate 'Groups' %}</strong></td></tr>
<tr>
<td class="table-light">
    <div class="d-flex flex-wrap"> 
    {% for z in group.subgroups.all %}
    <a class="btn btn-success btn-sm mx-1 my-1" href="{% url 'app_user:group_detail' z.keyname %}" role="button">
    {{ z.keyname }}</a>{% endfor %} 
    {% for z in subgroups_indirect %}
    <a class="btn btn-outline-success btn-sm mx-1 my-1" href="{% url 'app_user:group_detail' z.keyname %}" role="button">
    {{ z.keyname }}</a>{% endfor %} 
    </div>    
</td></tr>
</table>


    <!-- DELETE CONFIRM Modal -->
    {% if group %}

    <div class="modal fade" id="DeleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
    <div class="modal-dialog">
    <div class="modal-content">

    <div class="modal-header">
    <h1 class="modal-title fs-5" id="staticBackdropLabel">{% translate "Confirm delete ?" %}</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
        
    <div class="modal-body">
    <p>Group: {{ group.keyname|default:'n/a' }}</p>
    </div>

    <div class="modal-footer">
    <form action="{% url 'app_user:group_delete' group.id %}" method="post">{% csrf_token %}
    <button role="button" class="btn btn-danger">{% translate "Delete" %}</button>
    <a role="button" class="btn btn-outline-dark" data-dismiss="modal">{% translate "Cancel" %}</a>
    </form>
    </div>

    </div>
    </div>
    </div>
    {% endif %}


{% endblock %}

archive/3.14.0/django/app_user/templates/app_user/group_edit.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_user/_navbar_app.html' %}
{% endblock %}


{% block title %}
{% if group.keyname %} <H2>{% translate "Group" %}: {{ group.keyname }}</H2>
{% else %}<H2>{% translate "New Group" %}</H2>
{% endif %} 
<hr>
{% endblock %}


{% block content %}

<form method="post">{% csrf_token %}

<a class="btn btn-outline-dark" onclick="history.back()" role="button">
<i class="fa fa-backward" aria-hidden="true"></i>&nbsp; {% translate 'Back' %} </a>

{% if 'p_group_update' in aaa.perms %}
<input class="btn btn-success" type="submit" value="{% translate 'Save' %}" name="save">
{% endif %}

{% if group %}
  {% if 'p_group_delete' in aaa.perms %}
  <button type="button" class="btn btn-danger float-right" data-bs-toggle="modal" data-bs-target="#DeleteModal">
  {% translate "Delete" %}
  </button>
  {% endif %}
{% endif %}

<hr>

<table class="table ">
  {{ form.as_table }}

    <tr>
    <th><label for="id_users">{% translate 'Users' %}</label></th>
    <td>
      <select name="users" id="id_users" multiple>
        <option value="">----------------------</option>
        {% for u in users %}
        {% if u.selected %}<option value="{{ u.key }}" selected>{{u.key}} ({{ u.display }})</option>
        {% else %}<option value="{{ u.key }}">{{u.key}} ({{ u.display }})</option>{% endif %}
        {% endfor %}
      </select>
    <br>
    <span class="helptext" id="id_users_helptext">{% translate 'Select users' %}</span>
    </td>
    </tr>

</table>

</form>


{% if group %}
<!-- DELETE CONFIRM Modal -->
<div class="modal fade" id="DeleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">

<div class="modal-header">
<h1 class="modal-title fs-5" id="staticBackdropLabel">{% translate "Confirm delete ?" %}</h1>
<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
    
<div class="modal-body">
<p>Group: {{ form.keyname.value|default:'n/a' }}</p>
</div>

<div class="modal-footer">
<form action="{% url 'app_user:group_delete' group.id %}" method="post">{% csrf_token %}
<button role="button" class="btn btn-danger">{% translate "Delete" %}</button>
<a role="button" class="btn btn-outline-dark" data-bs-dismiss="modal">{% translate "Cancel" %}</a>
</form>
</div>

</div>
</div>
</div>
{% endif %}


{% endblock %}




{% block script %}
<script type="text/javascript">

// USERS

//$(document).ready(function() {
//    $('#id_users').select2({
//      width: '100%'
//  });
//});

$('#id_users').select2({
  width: '100%',
  ajax: {
    url: "{% url 'app_user:ajax_user' %}",
    dataType: 'json',
    delay: 250,
    cache: true,
    data: function (params) {
      return {
        q: params.term
      };
    }
  },
  placeholder: '{% translate "Select users" %}'
  //minimumInputLength: 1
});


// PERMISSIONS
$(document).ready(function() {
    $('#id_subgroups').select2({
      width: '100%'
  });
});

// GROUPS

$(document).ready(function() {
    $('#id_permissions').select2({
      width: '100%'
  });
});
</script>
{% endblock %}

archive/3.14.0/django/app_user/templates/app_user/private.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_user/_navbar_app.html' %}
{% endblock %}



{% block title %}
<h1>{% translate 'People, Groups and Roles' %}</h1><hr>

{% endblock %}


{% block content %}
<a href="{% url 'app_user:user_list' %}" class="btn btn-primary">Users</a>
<a href="{% url 'app_user:group_list' %}" class="btn btn-primary">Groups</a>
<a href="{% url 'app_user:role_list' %}" class="btn btn-primary">Roles</a>

<hr>
{% endblock %}

archive/3.14.0/django/app_user/templates/app_user/role_detail.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_user/_navbar_app.html' %}
{% endblock %}

{% block title %}
<h3>{{ role.displayname|default:role.keyname }}</h3>
<small class="text-muted">{% translate "Role details" %}</small>
<hr>{% endblock %}

{% block content %}

<!-- TOOLS  -->
<a class="btn btn-outline-dark" href="{% url 'app_user:role_list' %}" role="button">
<i class="fa fa-backward" aria-hidden="true"></i>&nbsp;{% translate "Back" %} </a>

{% if 'p_role_update' in aaa.perms %}
  <a class="btn btn-success" href="{% url 'app_user:role_edit' role.id %}" role="button">
  {% translate 'Edit' %}</a>
{% endif %}

{% if 'p_role_delete' in aaa.perms %}
  {% if not role.is_builtin %}
  <a type="button" class="btn btn-danger float-right" data-bs-toggle="modal" data-bs-target="#DeleteModal">
  {% translate "Delete" %}</a>
  {% endif %}
{% endif %}

<hr>

<table class="table table-hover table-bordered table-sm">

  <tr class="table-success"><td colspan="2"><strong>{% translate 'Role' %}</strong></td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Keyname(*)' %}</td>
  <td>{{ role.keyname }}</td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Display Name' %}</td>
  <td>{{ role.displayname }}</td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Is Enabled' %}</td>
  <td>{% if role.is_enabled %}<input type="checkbox" checked disabled/>
      {% else %}<input type="checkbox" disabled/>{% endif %}
  </td></tr>

  <tr><td class="table-light" width="20%">{% translate 'Built-in' %}</td>
  <td>{% if role.is_builtin %}<input type="checkbox" checked disabled/>
      {% else %}<input type="checkbox" disabled/>{% endif %}
  </td></tr>

</table>

<hr>    

<!-- USERS -->
<table class="table table-hover table-bordered table-sm">
<tr class="table-primary"><td colspan="4"><strong>{% translate 'Users' %}</strong></td></tr>
<tr>
<td class="table-light">
    <div class="d-flex flex-wrap"> 
    {% for z in role.users.all %}
    <a class="btn btn-primary btn-sm mx-1 my-1" href="{% url 'app_user:user_detail' z.login %}" role="button">
    {{ z.login }}</a>{% endfor %}     
    {% for z in users_indirect %}
    <a class="btn btn-outline-primary btn-sm mx-1 my-1" href="{% url 'app_user:user_detail' z.login %}" role="button">
    {{ z.login }}</a>{% endfor %}     
    </div>  
</td></tr>
</table>

<!-- SUBGROUPS -->
<table class="table table-hover table-bordered table-sm">
<tr class="table-success"><td colspan="4"><strong>{% translate 'Groups' %}</strong></td></tr>
<tr>
<td class="table-light">
    <div class="d-flex flex-wrap"> 
    {% for z in role.subgroups.all %}
    <a class="btn btn-success btn-sm mx-1 my-1" href="{% url 'app_user:group_detail' z.keyname %}" role="button">
    {{ z.keyname }}</a>{% endfor %}   
    {% for z in subgroups_indirect %}
    <a class="btn btn-outline-success btn-sm mx-1 my-1" href="{% url 'app_user:group_detail' z.keyname %}" role="button">
    {{ z.keyname }}</a>{% endfor %}   
    </div>   
</td></tr>
</table>


<!-- PERMISSIONS -->
<table class="table table-hover table-bordered table-sm">
<tr class="table-warning"><td colspan="4"><strong>{% translate 'Permissions' %}</strong></td></tr>
<tr>
{% for perm in role.permissions.all %}
<td class="table-light" width="20%">{{ perm.keyname }}</td>
<td>{{ perm.appname|default:'' }}</td>
<td>{{ perm.displayname|default:'' }}</td>
<td>{{ perm.description|default:'' }}</td>
</tr>{%  endfor %}
</table>




<!-- DELETE CONFIRM Modal -->
    {% if role %}

    <div class="modal fade" id="DeleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">

    <div class="modal-header">
    <h1 class="modal-title fs-5" id="staticBackdropLabel">{% translate "Confirm delete ?" %}</h1>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
        
    <div class="modal-body">
    <p>Role: {{ role.keyname|default:'n/a' }}</p>
    </div>

    <div class="modal-footer">
    <form action="{% url 'app_user:role_delete' role.id %}" method="post">{% csrf_token %}
    <button role="button" class="btn btn-danger">{% translate "Delete" %}</button>
    <a role="button" class="btn btn-outline-dark" data-dismiss="modal">{% translate "Cancel" %}</a>
    </form>
    </div>

    </div>
    </div>
    </div>
    {% endif %}


{% endblock %}

archive/3.14.0/django/app_user/templates/app_user/role_edit.html
{% extends "app_home/base.html" %}
{% load static %}
{% load i18n %}

{% block navbar_app %}
{% include 'app_user/_navbar_app.html' %}
{% endblock %}


{% block title %}
{% if role.keyname %} <H2>{% translate "Role" %}: {{ role.keyname }}</H2>
{% else %}<H2>{% translate "New Role" %}</H2>
{% endif %} 
<hr>
{% endblock %}


{% block content %}

<form method="post">{% csrf_token %}

<a class="btn btn-outline-dark" href="{% url 'app_user:role_list' %}" role="button">
<i class="fa fa-backward" aria-hidden="true"></i>&nbsp;{% translate "Back" %} </a>

<input class="btn btn-success" type="submit" value="{% translate 'Save' %}" name="save">



<hr>

<table class="table ">
  {{ form.as_table }}
    <tr>
    <th><label for="id_users">{% translate 'Users' %}</label></th>
    <td>
      <select name="users" id="id_users" multiple>
        <option value="">----------------------</option>
        {% for u in users %}
        {% if u.selected %}<option value="{{ u.key }}" selected>{{u.key}} ({{ u.display }})</option>
        {% else %}<option value="{{ u.key }}">{{u.key}} ({{ u.display }})</option>{% endif %}
        {% endfor %}
      </select>
    <br>
    <span class="helptext" id="id_users_helptext">{% translate 'Select users' %}</span>
    </td>
    </tr>

</table>

</form>


{% if role %}
<!-- DELETE CONFIRM Modal -->
<div class="modal fade" id="DeleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">

<div class="modal-header">
<h1 class="modal-title fs-5" id="staticBackdropLabel">{% translate "Confirm delete ?" %}</h1>
<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
    
<div class="modal-body">
<p>Role: {{ form.keyname.value|default:'n/a' }}</p>
</div>

<div class="modal-footer">
<form action="{% url 'app_user:role_delete' role.id %}" method="post">{% csrf_token %}
<button role="button" class="btn btn-danger">{% translate "Delete" %}</button>
<a role="button" class="btn btn-outline-dark" data-dismiss="modal">{% translate "Cancel" %}</a>
</form>
</div>

</div>
</div>
</div>
{% endif %}


{% endblock %}




{% block script %}
<script type="text/javascript">

// USERS

//$(document).ready(function() {
//    $('#id_users').select2({
//      width: '100%'
//  });
//});

$('#id_users').select2({
  width: '100%',
  ajax: {
    url: "{% url 'app_user:ajax_user' %}",
    dataType: 'json',
    delay: 250,
    cache: true,
    data: function (params) {
      return {
        q: params.term
      };
    }
  },
  placeholder: '{% translate "Select users" %}'
  //minimumInputLength: 1
});

$(document).ready(function() {
    $('#id_subgroups').select2({
      width: '100%'
  });
});

$(document).ready(function() {
    $('#id_permissions').select2({
      width: '100%'
  });
});
</script>
{% endblock %}